### ISSUE TITLE
Link new config generator

### ISSUE THREAD

**Issue by nmxcgeo** [mozilla/http-observatory-website#200]
As a new [config generator](https://ssl-config.mozilla.org/) has been built, I think it is appropriate to replace all the [old links](https://github.com/mozilla/http-observatory-website/search?q=ssl-config-generator&unscoped_q=ssl-config-generator).

Greetings
Nmxcgeo

**Comment by april** [comment]
This was fixed in b4e4c621240998a1573cc0b2623bc760e40c328b, thanks for letting me know.

**Comment by nmxcgeo** [comment]
I don't think it was already completely fixed. I still get results for the [above link](https://github.com/mozilla/http-observatory-website/search?q=ssl-config-generator&unscoped_q=ssl-config-generator) and if you check a website with the observatory you get "Teleport me to Mozilla's config generator!" with the old link.
